fix: suppress adplaying when outside of an ad break
muxinc/mux-stats-sdk-media3 pull request #102
Opened 2024-11-20 19:54 UTC by andrewjl-mux

2024-11-20 23:44 UTC, cjpillsbury requested changes
On a quick glance only nits and minor suggestions. Otherwise, LGTM!

2024-11-20 23:44 UTC, cjpillsbury commented on library/src/main/java/com/mux/stats/sdk/muxstats/MuxStatsSdkMedia3.kt
> +import com.mux.android.util.oneOf
nitpick: Unused (assuming vestigial from a refactor). Remove.

2024-11-20 23:44 UTC, cjpillsbury commented on library/src/main/java/com/mux/stats/sdk/muxstats/MuxStatsSdkMedia3.kt
> +    } else {
nitpick: `else if` vs. `else` + (nested) `if`?

2024-11-20 23:44 UTC, cjpillsbury commented on library/src/test/java/com/mux/stats/sdk/muxstats/AdCollectorTests.kt
> +    Assert.assertTrue(
suggestion(non-blocking): use a loop + all expected filtered out ad events for your assertions. Alternatively, just write individual tests for every ad event like you did for the "allowed" ones, below (which allows test to better isolate an issue)

2024-11-20 23:47 UTC, andrewjl-mux commented on library/src/main/java/com/mux/stats/sdk/muxstats/MuxStatsSdkMedia3.kt
> +import com.mux.android.util.oneOf
c1899b3d97eb402767ee2889da25fdf425e75da2

2024-11-20 23:50 UTC, andrewjl-mux commented on library/src/main/java/com/mux/stats/sdk/muxstats/MuxStatsSdkMedia3.kt
> +    } else {
760e7d6ef45e0f33d7f77dcfea449f66a5a44e4b

2024-11-20 23:59 UTC, cjpillsbury approved these changes
👍

2024-11-21 00:05 UTC, daytime-em approved these changes
me three

2024-11-21 00:08 UTC, merged